version: 2.1

# Import the compare-url orb so we can get the git commit range
orbs:
  compare-url: iynere/compare-url@1.2.0

jobs:
  build:
    macos:
      xcode: "10.0"
    environment:
      HOMEBREW_DEVELOPER=1
      HOMEBREW_NO_AUTO_UPDATE=1
      HOMEBREW_COLOR=1
    steps:
      - checkout
      - restore_cache:
          key: homebrew
      - run:
          name: force strict error checking
          command: |
            # Force strict error checking.
            set -o errexit
            set -o pipefail
      - compare-url/reconstruct
      - compare-url/use:
          step-name: Update Travis commit range.
          custom-logic: |            
            BRANCH_COMMIT="${COMMIT_RANGE##*.}"
            TARGET_COMMIT="${COMMIT_RANGE%%.*}"
            if ! MERGE_BASE="$(git merge-base "${BRANCH_COMMIT}" "${TARGET_COMMIT}" 2>/dev/null)"; then
              git fetch --unshallow
              MERGE_BASE="$(git merge-base "${BRANCH_COMMIT}" "${TARGET_COMMIT}")"
            fi
            echo 'export TRAVIS_COMMIT_RANGE='"$MERGE_BASE...$BRANCH_COMMIT" >> $BASH_ENV
      - run:
          name: Switch to master branch.
          command: |
            # Switch to master branch.
            brew update-reset
      - run:
          name: "Fix CIRCLE_WORKING_DIRECTORY"
          command: echo 'CIRCLE_WORKING_DIRECTORY="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"' >> $BASH_ENV
      - run:
          name: Mirror the repo as a tap and run the ci cask.
          command: |
            # Mirror the repo as a tap.
            TAP_DIR="$(brew --repository)/Library/Taps/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"            
            mkdir -p ${TAP_DIR}            
            rsync -az --delete "${CIRCLE_WORKING_DIRECTORY}/" "${TAP_DIR}/"            
            export CIRCLE_WORKING_DIRECTORY="${TAP_DIR}"
            builtin cd "${CIRCLE_WORKING_DIRECTORY}"
            
            # Workaround so we don't run into permission issues
            sudo rm -rf /Library/LaunchDaemons/com.circleci.pfctl.plist
            
            # Run the script
            brew cask ci
      - save_cache:
          key: homebrew
          paths:
            - /usr/local/Homebrew/Library/Homebrew
